name: simple api example CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        - uses: actions/checkout@v2
      
      - name: Setup Go
        - uses: actions/setup-go@v2
          with:
            go-version: "1.16"
        - run: go mod tidy

      - name: Create test .env
        - run: mv .env.example .env
      - name: Test
        - run: go test ./test
