name: Build docker image
on:
  pull_request:
    branches:
      - main
    types: [closed]
# on:
#   workflow_run:
#     workflows: ["simple api example CI"]
#     branches: [main]
#     types: 
#       - completed
jobs:
  push_to_registry:
    environment: dockerhub
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - run: chmod 775 ./extract-image-tag_linux_amd64 
      - run: TAG=`./extract-image-tag_linux_amd64 -f simple-api.yml -tu https://registry.hub.docker.com/v1/repositories/a3magic3pocket/simple-web/tags`

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: a3magic3pocket/simple-api:${TAG}
