name: simple api example CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - run: go mod tidy
      - run: echo GIN_MODE=debug >> .env |
             echo IDENTITY_KEY=test-identity-key >> .env |
             echo AUTH_SECRET_KEY=test-auth-secret-key >> .env
      - run: go test ./test