name: simple api example CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Install dependencies
        run: go mod tidy

      - name: Create test .env
        run: mv .env.example .env

      - name: Test
        run: go test ./test

      - name: Image Tag Test
        run: chmod 775 ./extract-image-tag_linux_amd64 && ./extract-image-tag_linux_amd64 -f simple-api.yml -tu https://registry.hub.docker.com/v1/repositories/a3magic3pocket/simple-web/tags
on:
  [pull_request]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}

      - run: chmod 775 ./extract-image-tag_linux_amd64 
      - run: TAG=`./extract-image-tag_linux_amd64 -f simple-api.yml -tu https://registry.hub.docker.com/v1/repositories/a3magic3pocket/simple-web/tags`

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: a3magic3pocket/simple-api:${TAG}
